DROP TABLE IF EXISTS coords CASCADE;
CREATE TABLE coords (
  id SERIAL PRIMARY KEY NOT NULL,
  title text,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  latitude DECIMAL NOT NULL,
  longitude DECIMAL NOT NULL
);
